tap 'homebrew/core'
tap 'homebrew/bundle'
tap 'homebrew/cask'
tap 'homebrew/cask-fonts'
tap 'shivammathur/php'

# Install ZSH
brew 'zsh-completions'

# Install GNU core utilities (those that come with macOS are outdated)
brew 'coreutils'

# Install GNU `find`, `locate`, `updatedb`, and `xargs`, g-prefixed
brew 'findutils'


# Install Binaries
#brew 'fasd' Archived repo
brew 'tree'
brew 'the_silver_searcher'
brew 'hub'
brew 'wget'
brew 'bat'
brew 'graphviz'
brew 'tokei'
brew 'mkcert'
brew 'spaceship'


# NODE.JS
brew 'node'
brew 'pnpm'

# PHP
brew 'freetype'
brew 'jpeg'
brew 'libpng'
brew 'gd'
brew 'zlib'
#brew 'composer'
#brew 'php'
brew 'nginx'
brew 'php@5.6'

# Dev tools
brew 'mysql-client'

# MacOS apps
cask 'appzapper'
cask 'daisydisk'
cask 'insomnia'
cask 'keepingyouawake'
cask 'vlc'
# cask 'wkhtmltopdf'

# Quicklook
# cask 'qlcolorcode'
# cask 'qlmarkdown'
# cask 'quicklook-json'
# cask 'quicklook-csv'
# cask 'qlstephen'

# Fonts
cask 'font-source-code-pro-for-powerline'
cask 'font-source-code-pro'
cask 'font-jetbrains-mono-nerd-font'
cask 'font-fira-code'


