alias art='php artisan'
alias tinker='php artisan tinker'
alias php7='/usr/local/opt/php@7.4/bin/php'
alias php5='/usr/local/opt/php@5.6/bin/php'
#alias composer='php -c ~/dotfiles/php/disable-xdebug.ini /usr/local/bin/composer '
alias composer7='php7 -c ~/dotfiles/php/disable-xdebug.ini /usr/local/bin/composer '
alias composer5='php5 -c ~/dotfiles/php/disable-xdebug.ini ~/dotfiles/php/composer_2.2_lts.phar'
